### ISSUE TITLE
Error "metadata file not found" for .whl package files

### ISSUE THREAD

**Issue by mo-han** [montag451/pypi-mirror#4] opened 2019-11-11 03:19 UTC
Downloading is fine, all binary packages (.whl files) are downloaded successfully, too. However all .whl files are alone without corresponded meta files (like those .metadata.json files for the .tar.gz packages). Thus, when executing the create command, the "metadata file not found" error occurs and creating fails.

**Comment by montag451** [comment] 2019-11-11 12:45
Hi @mo-han,

I'm not able to reproduce your problem. Can you give me an example of a download command that fails to produce the metadata file?

**Comment by mo-han** [comment] 2019-11-14 06:09
```bat
pypi-mirror.exe -d d:\pypi-mirror\ download  -b -k cython
Looking in indexes: https://pypi.tuna.tsinghua.edu.cn/simple
Collecting cython
  Using cached https://pypi.tuna.tsinghua.edu.cn/packages/86/8f/7b3c6ca36ecd4bda3440c7d0c8cc92759ef773afb05dc6accd7a0108171d/Cython-0.29.14-cp35-cp35m-win32.whl
  Saved d:\pypi-mirror\cython-0.29.14-cp35-cp35m-win32.whl
Successfully downloaded cython
Failed to execute command 'download': error while processing 'd:\pypi-mirror\Cython-0.29.14-cp35-cp35m-win32.whl': metadata file not found
```

**Comment by mo-han** [comment] 2019-11-14 06:15
```bat
pypi-mirror.exe -d d:\pypi-mirror\ download  -b -k cython
Collecting cython
  Downloading https://files.pythonhosted.org/packages/86/8f/7b3c6ca36ecd4bda3440c7d0c8cc92759ef773afb05dc6accd7a0108171d/Cython-0.29.14-cp35-cp35m-win32.whl (1.5MB)
     |████████████████████████████████| 1.5MB 14kB/s
  Saved d:\pypi-mirror\cython-0.29.14-cp35-cp35m-win32.whl
Successfully downloaded cython
Failed to execute command 'download': error while processing 'd:\pypi-mirror\Cython-0.29.14-cp35-cp35m-win32.whl': metadata file not found
```

**Comment by montag451** [comment] 2019-11-16 18:25
I've pushed a new commit on the master branch. It should fix your problem. I will push a new version on PyPI as soon as you confirm that everything is OK on your side (I don't have a Windows machine to check).

**Comment by montag451** [comment] 2019-11-24 22:07
No news is good news. I've published a new release which should solve your issue so I close this issue. If you find out that your problem is not solved by this new release, feel free to re-open it.

**Closed as completed by montag451** 2019-11-24 22:07 UTC

**Comment by dacevedo12** [comment] 2023-02-01 20:45
I'm experiencing the same error with hypercorn

`Failed to execute command 'create': error while processing '/path/Hypercorn-0.14.3-py3-none-any.whl': metadata file not found`

https://files.pythonhosted.org/packages/be/8b/e856965857137bc594e8fd52fef1d00b79913a6a01033cba772276aff10b/Hypercorn-0.14.3-py3-none-any.whl

**Comment by dacevedo12** [comment] 2023-02-01 20:53
@montag451 I've tracked it down to the `get_metadata_from_wheel` function, which doesn't seem to consider casing.

this dependency was published to pypi as hypercorn (lower case) but the wheel file is Hypercorn (uppercase h). Weirdly enough, the directories inside the wheel are lowercase, which causes the error.

should I open a new issue or is it better to reopen this one?

**Comment by montag451** [comment] 2023-02-01 21:33
@dacevedo12 yes please, open a new issue
