### ISSUE TITLE
 Error: metadata file not found

### ISSUE THREAD

**Issue by rumeshkrish** [montag451/pypi-mirror#29] opened 2023-11-28 16:36 UTC
**Cmd:**
```
pypi-mirror create -d pypi-remote -m simple                                                   
```
**Result:**
```
Failed to execute command 'create': error while processing 'pypi-remote/PyQt5-5.8.1.1-5.8.0-cp35.cp36.cp37-none-win_amd64.whl': metadata file not found
To get further information re-run the script with --print-traceback 
```
another example
```
Failed to execute command 'create': error while processing 'pypi-remote/os_sys-1.9.3-py3-none-any.whl': metadata file not found
To get further information re-run the script with --print-traceback
```

**Comment by montag451** [comment] 2023-12-09 13:21
I will need more details to help you. Which version of Python are you using? Can you give me the command that you've used to download the packages that produce the errors?

**Comment by montag451** [comment] 2023-12-30 19:14
I can't reproduce your problem and without more information from you there is nothing I can do so I will close this issue. Feel free to reopen it if you want.

**Closed as not planned** 2023-12-30 19:14 UTC
